# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
